[package]
name = "spawn"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "spawn"
path = "src/main.rs"

[dependencies]
dotenv = "0.15.0"

[build-dependencies]
bootloader = { version = "0.11.17", default-features = false, features = ["bios"] }
kernel = { path = "../kernel", artifact = "bin", target = "x86_64-unknown-none" }
